spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      properties:
        schema.registry.url: "http://127.0.0.1:8081"
      group-id: "reporting-warehouse"
      value-deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

zenin:
  kafka:
    topic-pattern: "prod\\..*"
  json:
    timestampMode: UNIX